config/routes.rb
AtomicDigester::Application.routes.draw do

  get 'static_pages/index'

  root :to => "static_pages#index"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    resources :feeds
  end

  resources :feeds
  resources :stories, only: %i( index )

end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, Feed, user_id: user.id
      can :manage, User, id: user.id
    end
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base

  belongs_to :user

  validates :name, presence: true
  validates :url, presence: true
  validates :user_id, presence: true
  validate :validate_feed_url

  def stories
    # First check Redis to see if we get a cache hit.
    xml = $redis.get(cache_key)
    return wrap_entries(Feedjira::Feed.parse(xml).entries) if xml.present?

    # Then retrieve the XML from the server.
    xml = Feedjira::Feed.fetch_raw(url)

    # Make sure the XML is a String (indicating we got a response).
    raise Feedjira::NoParserAvailable unless xml.kind_of?(String)

    # Attempt to parse the XML.
    parsed = Feedjira::Feed.parse(xml)

    # Does the parsed result seem correct?
    raise Feedjira::NoParserAvailable unless parsed.respond_to?(:entries)

    # Cache the response and return it.
    $redis.setex(cache_key, cache_lifetime_seconds, xml)
    wrap_entries(parsed.entries)
  rescue Feedjira::NoParserAvailable
    # We got something in response that isn't parsable.
    $redis.setex(cache_key, cache_lifetime_seconds, YAML.dump(nil))
    return
  end

  def cache_lifetime_seconds
    15.minutes
  end

  def cache_key
    "feed_cache:#{ url }"
  end

  protected

  def validate_feed_url
    errors[:url] << "doesn't seem to be a valid rss feed" unless stories
  end

  def wrap_entries(entries)
    entries.map { |entry| Story.new self, entry }
  end

end

app/models/story.rb
class Story

  attr_reader :feed, :raw

  delegate :published,
           :author,
           :title,
           :summary,
           :url,
    to: :raw

  def initialize(feed, raw)
    @feed = feed
    @raw  = raw
  end

  def content
    html = raw.content
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :feeds

  def stories
    feeds.map(&:stories).flatten.sort_by(&:published)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/feeds_controller.rb
class FeedsController < InheritedResourceController

  respond_to :json

  belongs_to :user, optional: true

  load_and_authorize_resource :user
  load_and_authorize_resource :feed

  protected

  def permitted_params
    params.permit(feed: %i(
      name
      url
    ))
  end

end

app/controllers/inherited_resource_controller.rb
class InheritedResourceController < InheritedResources::Base

  include InheritedResources::DSL

  before_filter :authenticate_user!

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  respond_to :json

  load_and_authorize_resource :user

  def index
    @user ||= current_user
    @stories = @user.stories.reverse
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResourceController

  respond_to :json

  load_and_authorize_resource :user

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def decorated(objects, decorator_class = nil, &block)
    Array(objects).map do |object|
      if decorator_class == nil
        class_name = if object.respond_to?(:model_name) then object.model_name else object.class.name end
        decorator_name = "#{class_name}Decorator"
        decorator_name.constantize.new(object)
      else
        decorator_class.new(object)
      end
    end
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/home/index.html.haml
%h3 Home

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Feeds', user_feeds_path(current_user), class: 'navbar-brand' if current_user
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html{"ng-app" => "digester"}
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Atomic Digester'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Atomic Digester'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      /.col-md-6.col-md-offset-3= yield

app/views/static_pages/index.html.haml
%div{"ng-view" => true} AngularJS